version: '3.3'

services:
  database:
    container_name: database
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    volumes:
      - ./config/database/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql/data
    
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://database:5432/sonar_qube
      - SONAR_JDBC_USERNAME=admin
      - SONAR_JDBC_PASSWORD=admin123
    volumes:
      - sonarqube:/opt/sonarqube
    depends_on:
      - database
  
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    environment:
      JENKINS_USER: admin
      JENKINS_PASS: admin123
    volumes:
      - jenkins:/var/jenkins_home

  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - sonarqube
      - jenkins

volumes:
  database:
    driver: local
  sonarqube:
    driver: local
  jenkins:
    driver: local
